version: 2.1
orbs:
  docker: circleci/docker@1.1.0
jobs:
  build:
    docker:
      - image: cimg/node:17.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test Docker
          command: docker --version
      # - run:
      #     name: Start Docker
      #     command: sudo service docker start
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: /home/circleci/project/client
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/videodemo:latest .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/videodemo:latest
          working_directory: /home/circleci/project/client
       - run:
          name: Build and push Docker image Server
          command: |
            docker build -t $DOCKERHUB_USERNAME/videodemoServer:latest .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/videodemoServer:latest
          working_directory: /home/circleci/project/server/video-editing-api
workflows:
  build-and-deploy:
    jobs:
      - build
